### ISSUE TITLE
Access  pg_eventserv in secure mode in a container?

### ISSUE THREAD

**Issue by gamesbook** [pramsey/pg_eventserv#2]
I hope this request for help is not too far "out of scope".

We are trying to set up `pg_eventserv` as a key part of a Dockerised application.

Everything was built and tested and works as expected on an unsecured (no certificates) server.

However, we have not been able to find the correct setup that allows any application to interface with the `pg_eventserv` service in secure mode. (We have other applications running in secure mode and there has not been any problem with them, so we are confident the certificates are properly setup.)

All services below are run on the same server.

Here is the Apache config section that handles calls to the endpoint:
```
<VirtualHost *:80>
    ServerName ws.lmmp.mapit.co.za
    ServerAlias ws.lmmp.mapit.co.za
    ServerAdmin test@dummy.org
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    RewriteEngine On
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule .* wss://192.168.112.3:7701/$1 [P,L]
    ProxyPass / wss://192.168.112.3:7701/
    ProxyPassReverse / wss://192.168.112.3:7701/
    ProxyRequests Off
</VirtualHost>
```
(The "192.168.112.3" address is that of the container on the server, as reported by *Portainer*.)

The `pg_eventserv` section for compose file looks like this:
```
  events:
    image: pramsey/pg_eventserv
    container_name: lmmp_event
    ports:
      - "${EVENT_PORT}:7700"
      - "${EVENT_PORT_HTTPS}:7701"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - API_URI=http://api:3000
      - ES_TLSSERVERCERTIFICATEFILE=${SERVER_CRT}
      - ES_TLSSERVERPRIVATEKEYFILE=${SERVER_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
```

The settings for the variables in the `.env.` file are:
```
EVENT_PORT=7700
EVENT_PORT_HTTPS=7701
SERVER_CRT=/etc/ssl/certs/ca-certificates.crt
SERVER_KEY=/etc/ssl/private/ssl-cert-snakeoil.key

```

Here is an example of a Python script for testing access:
```
import websocket
import _thread
import rel

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws, close_status_code, close_msg):
    print("### closed WS connection ###")

def on_open(ws):
    print("### opened WS connection ###")

if __name__ == "__main__":
    ws = websocket.WebSocketApp(
        "wss://ws.lmmp.mapit.co.za/listen/delivery",
        on_open=on_open,
        on_message=on_message,
        on_error=on_error,
        on_close=on_close)

    ws.run_forever(dispatcher=rel, reconnect=10)
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch()
```
(in reality, we are using JavaScript to access the web socket ... but it reports a "1006" error code, saying *"Connection hung up abruptly"* when attempting to connect.)
